typography_spectrum: 0.7095381196122617
color:
  brandStrength: 0.1785289386752993
  lightness: 0.9101360137574375
  saturation: 0.6160684914793819
  rhythmicContrast: 0.7824265537783504
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.0473688286729157
author:
  name: Jan Marvin
  email: marvin.jan@gmail.com
name: Jan Marvin Art Studio
navigation:
  - name: Etsy Shop
    url: 'https://www.etsy.com/shop/JanMarvinArtStudio?ref=hdr_shop_menu'
    type: external
  - name: Amazon
    url: >-
      https://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=jan+marvin+art+of+joy
    type: external
  - name: Metallic Gold on Totes
    url: >-
      https://testing.thegrid.io/app/site/live?siteID=0173c412-f8d6-4a25-bcae-dd4a2b90fbb5
    type: external
title: Jan Marvin Art Studio
description: The 'Art of Joy'
