typography_spectrum: 0.904498542426154
color:
  brandStrength: 0.08751061651855707
  lightness: 0.038916432997211814
  saturation: 0.5698068782221526
  rhythmicContrast: 0.39113774918951094
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.5465245130471885
author:
  name: Jan Marvin
  email: marvin.jan@gmail.com
name: Jan Marvin Art Studio
navigation:
  - name: Etsy Shop
    url: 'https://www.etsy.com/shop/JanMarvinArtStudio?ref=hdr_shop_menu'
    type: external
  - name: Amazon
    url: >-
      https://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=jan+marvin+art+of+joy
    type: external
title: Jan Marvin Art Studio
description: The 'Art of Joy'
